/*
RUN SCRIPT IN PRD_DOCUMENTATION DATABASE!!
Group: Agency Assignments
*/
SELECT 
  	   [DMTF_TABLE_NAME]
      ,[TAB_PREFIX]
      ,[DMTF_FIELD_NAME]
      ,[ALIAS_FIELD_CAPTION]
      ,[ALIAS_FIELD_DESCRIPTION]
      ,[DMTF_FIELD_DATA_TYPE]
      ,[ALIAS_FIELD_TYPE]
      ,[ALIAS_LOOKUP_LIST]
FROM [PRD_Documentation].[dbo].[VW_DOC_TABLE_FIELDS]

WHERE DMTF_TABLE_NAME IN (
     'AT_ASSIGN_MODEL'
    ,'AT_ASSIGN_MODEL_CRIT'
    ,'AT_ASSIGNMENT_EXCEPTIONS'
    ,'AT_ASSIGNMENT_STREAM_EXCEPTIONS'
    ,'AT_CASE_STREAM_EXCLUSIONS'
    ,'AT_CASE_STREAM_EXCLUSIONS_HIST'
    ,'AT_COLLECTION_COMP_PARAMS'
    ,'AT_CUST_CASE_EXCL_LOG'
    ,'AT_EXTERNAL_COMPANIES'
    ,'AT_EXTERNAL_COMPANIES_ALIASES'
    ,'AT_EXTERNAL_COMPANIES_PERFORMANCE_DETAILS'
    ,'AT_EXTERNAL_COMPANIES_PERFORMANCE_EXCEPTIONS'
    ,'AT_EXTERNAL_COMPANIES_PERFORMANCE_FILES'
    ,'AT_EXTERNAL_COMPANIES_PERFORMANCE_HEADER'
    ,'AT_EXTERNAL_COMPANIES_PROCESS_TYPES'
    ,'AT_EXTERNAL_COMPANIES_REGIONS'
    ,'AT_EXTERNAL_COMPANY_AUTHORITIES'
    ,'AT_EXTERNAL_COMPANY_LAWYERS'
    ,'AT_EXTERNAL_COMPANY_STREAM_PACKET_TYPES'
    ,'AT_EXTERNAL_COMPANY_STREAMS'
    ,'AT_PACK_ASSIGN_SNAP'
    ,'AT_PACKET_ASSIGNMENT_ALGORITHMS'
    ,'AT_PACKET_ASSIGNMENT_DISTRIBUTION_METHODS'
    ,'AT_PACKET_COMPANIES'
    ,'AT_PACKET_COMPANY_CASES'
    ,'AT_PACKET_STRATEGY_STEPS'
    ,'AT_PACKET_WORK_LISTS'
    ,'AT_PACKETS'
    ,'AT_PARAMS_OF_COLLECTION_COMP'
    ,'AT_REGIONS'
    ,'AT_REGIONS_POSTAL_SECTORS'
    ,'AT_RETURNS'
    ,'AT_RETURNS_REASONS'
    ,'AT_REV_CASES'
    ,'AT_REV_CRITERIA'
    ,'AT_REV_CRITERIA_VALUES'
    ,'AT_REV_TYPE_STREAMS'
    ,'AT_REV_TYPES'
    ,'AT_REVOC_PACKET_COMPANIES'
    ,'AT_REVOCATIONS'
)
 ORDER BY DMTF_TABLE_NAME, COLUMN_ID