/*
CASES/CUSTOMERS/DEBTS
RUN SCRIPT IN PRD_DOCUMENTATION DATABASE!!
*/
SELECT 
  	   [DMTF_TABLE_NAME]
      ,[TAB_PREFIX]
      ,[DMTF_FIELD_NAME]
      ,[ALIAS_FIELD_CAPTION]
      ,[ALIAS_FIELD_DESCRIPTION]
      ,[ALIAS_FIELD_DATA_TYPE]
      ,[ALIAS_FIELD_TYPE]
      ,[ALIAS_LOOKUP_LIST]
FROM [PRD_Documentation].[dbo].[VW_DOC_TABLE_FIELDS]


 ORDER BY DMTF_TABLE_NAME, COLUMN_ID