/*
CASES/CUSTOMERS/DEBTS
RUN SCRIPT IN PRD_DOCUMENTATION DATABASE!!
*/
SELECT 
  	   [DMTF_TABLE_NAME]
      ,[TAB_PREFIX]
      ,[DMTF_FIELD_NAME]
      ,[ALIAS_FIELD_CAPTION]
      ,[ALIAS_FIELD_DESCRIPTION]
      ,[DMTF_FIELD_DATA_TYPE]
      ,[ALIAS_FIELD_TYPE]
      ,[ALIAS_LOOKUP_LIST]
FROM [PRD_Documentation].[dbo].[VW_DOC_TABLE_FIELDS]

WHERE DMTF_TABLE_NAME IN (
		 'AT_CASE_AGGREGATIONS'
		,'AT_CASE_BILLING'
		,'AT_CASE_CORE'
		,'AT_CASE_EXTRA'
		,'AT_CASE_EXTRA_CUSTOMERS'
		,'AT_CASE_PROPERTIES'
		,'AT_CASE_SCORING'
		,'AT_CASE_STATISTICS'
		,'AT_CASES'
		,'AT_CUSTOMER_ADDRESSES'
		,'AT_CUSTOMER_CONTACTS'
		,'AT_CUSTOMER_CORE'
		,'AT_CUSTOMER_EXTRA'
		,'AT_CUSTOMER_INTERNET_IDS'
		,'AT_CUSTOMER_MEMOS'
		,'AT_CUSTOMER_PHONES'
		,'AT_CUSTOMER_SCORING'
		,'AT_CUSTOMER_STATISTICS'
		,'AT_CUSTOMER_STATISTICS_BU'
		,'AT_CUSTOMERS'
		,'AT_CUSTOMERS_EXTENSION'
		,'AT_DEBT_ELEMENTS'
		,'AT_DEBT_ELEMENTS_GROUPING'
		,'AT_DEBT_ELEMENTS_GROUPING_MEMBERS'
		,'AT_DEBT_ITEM_MEMOS'
		,'AT_DEBT_ITEMS'
		,'AT_DEBT_ITEMS_EXTENSION'
		,'AT_DEBTS'
		,'AT_DEBTS_EXTENSION'
		,'AT_DEBTS_STATISTICS'
		,'AT_MOVED_CASES_APPLICATION'
		,'AT_MOVED_CASES_EXTRA'
		,'AT_MOVED_CASES_HOST'
		,'AT_MOVED_CASES_RESTORE_HISTORY'
		,'AT_MOVED_CASES_STATISTIC'
		,'EOD_CASES_CONTROL')
 ORDER BY DMTF_TABLE_NAME, COLUMN_ID