/*
RUN SCRIPT IN PRD_DOCUMENTATION DATABASE!!
*/

USE [QBCOLLECTION_PLUS_23_1]

SELECT 
	COL.[NAME] AS FIELD_NAME, 
	OBJECT_NAME(COL.OBJECT_ID) AS TABLE_NAME,
	ENTITY.FIELD_DESCRIPTION,
	AUX.FIELD_TYPE,
	COL.MAX_LENGTH,
	COL.PRECISION,
	COL.SCALE,
	CASE 
	WHEN T.NAME='NVARCHAR' THEN T.NAME + '(' + CONVERT(NVARCHAR,COL.MAX_LENGTH) + ')'
	WHEN T.NAME='DECIMAL' THEN T.NAME + '(' + CONVERT(NVARCHAR,COL.PRECISION) + ',' + CONVERT(NVARCHAR,COL.SCALE) +')'
	ELSE T.NAME
	END AS FIELD_DATATYPE,
		TAB.TAB_PREFIX,
	CASE WHEN FKC.REFERENCED_COLUMN_ID IS NULL THEN '' ELSE 'FK' END AS IS_FOREIGN_KEY
	FROM QBCOLLECTION_PLUS_23_1.SYS.COLUMNS COL WITH(NOLOCK)
	INNER JOIN QBCOLLECTION_PLUS_23_1.SYS.TABLES ST WITH(NOLOCK) ON ST.OBJECT_ID=COL.OBJECT_ID
	INNER JOIN QBCOLLECTION_PLUS_23_1.SYS.TYPES T ON COL.USER_TYPE_ID = T.USER_TYPE_ID
	INNER JOIN QBCOLLECTION_PLUS_23_1.DBO.TABLES TAB WITH(NOLOCK) ON TAB.TAB_NAME=OBJECT_NAME(COL.OBJECT_ID)
	LEFT JOIN QBCOLLECTION_PLUS_23_1.SYS.FOREIGN_KEY_COLUMNS FKC WITH(NOLOCK) ON FKC.PARENT_COLUMN_ID=COL.COLUMN_ID AND FKC.PARENT_OBJECT_ID=ST.OBJECT_ID
	LEFT JOIN PRD_DOCUMENTATION.DBO.AUX_WORKSHEET AUX WITH(NOLOCK) ON AUX.TABLE_NAME=ST.NAME AND AUX.FIELD_NAME=COL.NAME
	LEFT JOIN PRD_DOCUMENTATION.DBO.ENTITY_WORKSHEET ENTITY WITH(NOLOCK) ON ENTITY.ENTITY_WORKSHEET=AUX.ENTITY_WORKSHEET AND ENTITY.AUX_WORKSHEET=AUX.AUX_WORKSHEET AND ENTITY.DRIVER_DB_FIELD=COL.NAME

WHERE ST.NAME IN (
		 'AT_CASE_AGGREGATIONS'
		,'AT_CASE_BILLING'
		,'AT_CASE_CORE'
		,'AT_CASE_EXTRA'
		,'AT_CASE_EXTRA_CUSTOMERS'
		,'AT_CASE_PROPERTIES'
		,'AT_CASE_SCORING'
		,'AT_CASE_STATISTICS'
		,'AT_CASES'
		,'AT_CUSTOMER_ADDRESSES'
		,'AT_CUSTOMER_CONTACTS'
		,'AT_CUSTOMER_CORE'
		,'AT_CUSTOMER_EXTRA'
		,'AT_CUSTOMER_INTERNET_IDS'
		,'AT_CUSTOMER_MEMOS'
		,'AT_CUSTOMER_PHONES'
		,'AT_CUSTOMER_SCORING'
		,'AT_CUSTOMER_STATISTICS'
		,'AT_CUSTOMER_STATISTICS_BU'
		,'AT_CUSTOMERS'
		,'AT_CUSTOMERS_EXTENSION'
		,'AT_DEBT_ELEMENTS'
		,'AT_DEBT_ELEMENTS_GROUPING'
		,'AT_DEBT_ELEMENTS_GROUPING_MEMBERS'
		,'AT_DEBT_ITEM_MEMOS'
		,'AT_DEBT_ITEMS'
		,'AT_DEBT_ITEMS_EXTENSION'
		,'AT_DEBTS'
		,'AT_DEBTS_EXTENSION'
		,'AT_DEBTS_STATISTICS'
		,'AT_MOVED_CASES_APPLICATION'
		,'AT_MOVED_CASES_EXTRA'
		,'AT_MOVED_CASES_HOST'
		,'AT_MOVED_CASES_RESTORE_HISTORY'
		,'AT_MOVED_CASES_STATISTIC')
 ORDER BY TAB.TAB_NAME, COL.COLUMN_ID



